/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    String message = "ㅓㅏㅁ니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니닐ㅇ";
    
    public static void main(String[] args) {
        System.out.println("Everybody Isolating in microcosm");
        System.out.println("암더 코리안 탑클래스 힙합모범 노블레스 페뷸러스 터뷸러스 골저스 벗 댕져러스 비트를 비틀어 제껴버리는 서브미션 챔피언");
    }
}