<<<<<<< HEAD
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    String message = "ㅓㅏㅁ니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니닐ㅇ";
    
    public static void main(String[] args) {
        System.out.println("Everybody Isolating in microcosm");
        System.out.println("포로리야~~");
        System.out.println("때릴꼬야?");
=======

public class App {
	static int a=77;
    // 인사 문구를 저장하는 변수
    String message = "ㅓㅏㅁ니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니니닐ㅇ";
    
    public String getGreeting() {
        return "Hiiiiiiiiiiiiiiiiiiiii!.";
>>>>>>> branch 'master' of https://github.com/injin/java110-team-project.git
    }
 
    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        System.out.println("aaaaaaa");
        System.out.println("ㅇㅇㅇ"); 
    }
}
